version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
    ports: 
      - "5173:5173"
    networks: 
      - app-network   
    
  backend:
    build: 
      context: ./backend # Path to the backend directory, where Dockerfile is located  
    volumes: 
      - ./backend/src:/app/src
    ports: 
    - "5000:5000"
    # env_file:
    #   - ./backend/.env
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=PERNDB
    depends_on:
     - db
    networks:
      - app-network
    
  db: 
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_DB: PERNDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      
    ports: 
    - "5432:5432"
    volumes: 
    - "pgdata:/var/lib/postgresql/data"
    networks:
    - app-network
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports: 
    - "5051:80"
    environment:
    - PGADMIN_DEFAULT_EMAIL=name@example.com 
    - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - db

volumes: 
  pgdata:
    # driver: 

networks:
  app-network:
    driver: bridge